### ISSUE TITLE
Add webpack-cli

### ISSUE THREAD

**Issue by MatheusRV** [sandoche/Jekyll-webpack-boilerplate#22]
After run: `npm run start` i get this error.

```
[0] The CLI moved into a separate package: webpack-cli
[0] Please install 'webpack-cli' in addition to webpack itself to use the CLI
[0] -> When using npm: npm i -D webpack-cli
[0] -> When using yarn: yarn add -D webpack-cli
[0] internal/modules/cjs/loader.js:638
[0]     throw err;
[0]     ^
[0]
[0] Error: Cannot find module 'webpack-cli/bin/config-yargs'
[0]     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
[0]     at Function.Module._load (internal/modules/cjs/loader.js:562:25)
[0]     at Module.require (internal/modules/cjs/loader.js:692:17)
[0]     at require (internal/modules/cjs/helpers.js:25:18)
[0]     at Object.<anonymous> (/mnt/d/Cloud/GitHub/matheu.srv.br/node_modules/webpack-dev-server/bin/webpack-dev-server.js:65:1)
[0]     at Module._compile (internal/modules/cjs/loader.js:778:30)
[0]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
[0]     at Module.load (internal/modules/cjs/loader.js:653:32)
[0]     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
[0]     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
[0] webpack-dev-server --env=dev exited with code 1
[1] Configuration file: /mnt/d/Cloud/GitHub/matheu.srv.br/_config.yml
[1]             Source: /mnt/d/Cloud/GitHub/matheu.srv.br
[1]        Destination: /mnt/d/Cloud/GitHub/matheu.srv.br/_site
[1]  Incremental build: disabled. Enable with --incremental
[1]       Generating...
[1] Building site for default language: "pt-br" to: /mnt/d/Cloud/GitHub/matheu.srv.br/_site
[1] Loading translation from file /mnt/d/Cloud/GitHub/matheu.srv.br/_i18n/pt-br.yml
[1]   Liquid Exception: No such file or directory @ rb_sysopen - /mnt/d/Cloud/GitHub/matheu.srv.br/_i18n/pt-br.yml in /_layouts/default.html
[1] jekyll 3.6.3 | Error:  No such file or directory @ rb_sysopen - /mnt/d/Cloud/GitHub/matheu.srv.br/_i18n/pt-br.yml
[1] bundle exec jekyll serve exited with code 1
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Then it works.

**Comment by sandoche** [comment]
Hi, have you installed the Ruby dependencies ?
Try to run `bundler install`

**Comment by MatheusRV** [comment]
After add webpack-cli in package it work!
